TEST override users permissions

diff --git a/assets/setup b/assets/setup
--- a/assets/setup
+++ b/assets/setup
@@ -47,6 +47,24 @@ ln -s /opt/gitlab/sv/sshd /opt/gitlab/service
 ln -sf /opt/gitlab/embedded/bin/sv /opt/gitlab/init/sshd
 mkdir -p /var/log/gitlab/sshd
 
+# Start service manager
+echo "Starting services..."
+GITLAB_OMNIBUS_CONFIG= /opt/gitlab/embedded/bin/runsvdir-start &
+
+echo "Configuring GitLab..."
+gitlab-ctl reconfigure
+
+# Make sure PostgreSQL is at the latest version.
+# If it fails, print a message with a workaround and exit
+if [ "${GITLAB_SKIP_PG_UPGRADE}" != true ]; then
+    gitlab-ctl pg-upgrade -w || failed_pg_upgrade
+fi
+
+if [ -n "${GITLAB_POST_RECONFIGURE_SCRIPT+x}" ]; then
+  echo "Runnning Post Reconfigure Script..."
+  eval "${GITLAB_POST_RECONFIGURE_SCRIPT}"
+fi
+
 chmod -R a+rwx /opt/gitlab
 chown -R 1001:0 /opt/gitlab
 
@@ -58,4 +76,3 @@ chown -R 1001:0 /etc/gitlab
 
 chmod -R a+rwx /var/log/gitlab
 chown -R 1001:0 /var/log/gitlab
-
